/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Dec 30 09:50:55 GMT 2021
 */

package rx.concurrency;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class TestScheduler_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "rx.concurrency.TestScheduler"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "US"); 
    java.lang.System.setProperty("user.dir", "/home/CIN/lmps2/semantic-conflict-study/SMAT/output-test-dest/RxJava/1c47b0cb26e6d971eefa42ebb3479099236b0125/evosuite_12"); 
    java.lang.System.setProperty("user.home", "/home/CIN/lmps2"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "lmps2"); 
    java.lang.System.setProperty("user.timezone", "America/Recife"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TestScheduler_ESTest_scaffolding.class.getClassLoader() ,
      "rx.operators.OperationSynchronize$Synchronize",
      "rx.operators.OperationZip$ZipObserver",
      "rx.plugins.RxJavaObservableExecutionHook",
      "rx.operators.OperationInterval$Interval",
      "rx.util.functions.FunctionLanguageAdaptor",
      "rx.operators.OperationThrottle$ThrottledOnNext",
      "rx.plugins.RxJavaPlugins",
      "rx.operators.OperationSubscribeOn$SubscribeOn",
      "rx.operators.OperationMaterialize$MaterializeObservable",
      "rx.operators.OperationTakeLast$TakeLast",
      "rx.operators.OperationThrottle$ThrottledOnError",
      "rx.operators.OperationTake$Take",
      "rx.operators.OperationThrottle$Throttle",
      "rx.operators.OperationGroupBy$GroupBy",
      "rx.operators.OperationMerge$MergeObservable$MergeSubscription",
      "rx.operators.OperationToObservableIterable$ToObservableIterable",
      "rx.Scheduler$10",
      "rx.Scheduler$11",
      "rx.util.SynchronizedObserver$UnitTest$TestMultiThreadedObservable",
      "rx.subjects.Subject",
      "rx.operators.OperationTakeWhile$TakeWhile",
      "rx.concurrency.CurrentThreadScheduler$UnitTest",
      "rx.operators.OperationOnErrorResumeNextViaFunction$OnErrorResumeNextViaFunction",
      "rx.operators.OperationToObservableSortedList$ToObservableSortedList$DefaultComparableFunction",
      "rx.util.AtomicObservableSubscription",
      "rx.operators.OperationMergeDelayError$MergeDelayErrorObservable",
      "rx.concurrency.ImmediateScheduler$1",
      "rx.operators.OperationToObservableFuture$ToObservableFuture",
      "rx.operators.OperationTakeUntil$SourceObservable",
      "rx.util.functions.Func1",
      "rx.util.functions.Func2",
      "rx.util.functions.Func0",
      "rx.Observable$ThrowObservable",
      "rx.operators.OperationCombineLatest$Aggregator",
      "rx.concurrency.DiscardableAction",
      "rx.subjects.ReplaySubject$DelegateSubscriptionFunc",
      "rx.util.functions.Func9",
      "rx.util.functions.Func7",
      "rx.util.functions.Func8",
      "rx.util.functions.Func5",
      "rx.util.functions.Functions",
      "rx.util.functions.Func6",
      "rx.Observable$NeverObservable",
      "rx.operators.OperationDematerialize$DematerializeObservable",
      "rx.util.functions.Func3",
      "rx.util.functions.Func4",
      "rx.subscriptions.CompositeSubscription",
      "rx.util.functions.Function",
      "rx.operators.OperationMap$MapObservable",
      "rx.operators.OperationCombineLatest$CombineObserver",
      "rx.concurrency.CurrentThreadScheduler$TimedAction",
      "rx.Scheduler$1$1",
      "rx.operators.OperationFilter$Filter",
      "rx.util.functions.FuncN",
      "rx.operators.OperationConcat$ConcatSubscription",
      "rx.util.functions.Action0",
      "rx.concurrency.ExecutorScheduler",
      "rx.util.functions.Action3",
      "rx.util.functions.Action2",
      "rx.operators.OperationToObservableList$ToObservableList",
      "rx.util.functions.Action1",
      "rx.concurrency.TestScheduler$1",
      "rx.operators.OperationFinally$Finally",
      "rx.operators.OperationSkip$Skip",
      "rx.operators.OperationObserveOn$ObserveOn",
      "rx.concurrency.ImmediateScheduler",
      "rx.concurrency.SleepingAction",
      "rx.Scheduler",
      "rx.Observer",
      "rx.observables.ConnectableObservable",
      "rx.concurrency.TestScheduler",
      "rx.operators.OperationOnErrorResumeNextViaObservable$OnErrorResumeNextViaObservable",
      "rx.concurrency.TestScheduler$CompareActionsByTime",
      "rx.operators.OperationScan$Accumulator",
      "rx.Subscription",
      "rx.subscriptions.BooleanSubscription",
      "rx.operators.OperationThrottle$ThrottledOnComplete",
      "rx.Scheduler$3",
      "rx.operators.OperationSubscribeOn$ScheduledSubscription",
      "rx.Scheduler$1",
      "rx.Scheduler$2",
      "rx.Scheduler$7",
      "rx.Scheduler$8",
      "rx.Scheduler$5",
      "rx.operators.OperatorTester$UnitTest$ForwardingScheduler",
      "rx.operators.OperationZip$Aggregator",
      "rx.plugins.RxJavaObservableExecutionHookDefault",
      "rx.Scheduler$9",
      "rx.operators.OperationSample$Sample",
      "rx.subscriptions.Subscriptions",
      "rx.Observable",
      "rx.operators.OperationAll$AllObservable",
      "rx.util.functions.Functions$Identity",
      "rx.subjects.ReplaySubject$SubscriptionFunc",
      "rx.operators.OperatorTester",
      "rx.operators.OperationOnErrorReturn$OnErrorReturn",
      "rx.operators.OperationMerge$MergeObservable",
      "rx.operators.OperationTakeUntil$OtherObservable",
      "rx.operators.OperationToObservableSortedList$ToObservableSortedList",
      "rx.concurrency.TestScheduler$TimedAction",
      "rx.subscriptions.Subscriptions$1",
      "rx.operators.OperationMergeDelayError$MergeDelayErrorObservable$MergeSubscription",
      "rx.subscriptions.Subscriptions$4",
      "rx.util.AtomicObservableSubscription$1",
      "rx.concurrency.NewThreadScheduler",
      "rx.concurrency.CurrentThreadScheduler$1",
      "rx.util.functions.Functions$AlwaysTrue",
      "rx.util.SynchronizedObserver$UnitTest$TestSingleThreadedObservable",
      "rx.concurrency.NewThreadScheduler$1",
      "rx.subjects.ReplaySubject$RepeatSubjectSubscription",
      "rx.operators.OperatorTester$UnitTest",
      "rx.concurrency.CurrentThreadScheduler"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("rx.util.functions.Func0", false, TestScheduler_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("rx.util.functions.Func2", false, TestScheduler_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(TestScheduler_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "rx.Scheduler",
      "rx.concurrency.TestScheduler",
      "rx.concurrency.TestScheduler$TimedAction",
      "rx.concurrency.TestScheduler$1",
      "rx.concurrency.TestScheduler$CompareActionsByTime",
      "rx.concurrency.SleepingAction",
      "rx.subscriptions.BooleanSubscription",
      "rx.concurrency.CurrentThreadScheduler",
      "rx.subscriptions.Subscriptions$4",
      "rx.subscriptions.Subscriptions",
      "rx.concurrency.ImmediateScheduler",
      "rx.Scheduler$5",
      "rx.concurrency.NewThreadScheduler",
      "rx.Scheduler$3",
      "rx.util.AtomicObservableSubscription$1",
      "rx.util.AtomicObservableSubscription",
      "rx.concurrency.NewThreadScheduler$1",
      "rx.Scheduler$7",
      "rx.Scheduler$10",
      "rx.Scheduler$1",
      "rx.Scheduler$2",
      "rx.subscriptions.Subscriptions$1",
      "rx.Scheduler$11",
      "rx.concurrency.DiscardableAction",
      "rx.concurrency.CurrentThreadScheduler$TimedAction",
      "rx.subscriptions.CompositeSubscription",
      "rx.Scheduler$9",
      "rx.Scheduler$1$1",
      "rx.Scheduler$8"
    );
  }
}
