/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 09 06:43:33 GMT 2021
 */

package org.elasticsearch.rest.action.cat;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.elasticsearch.cluster.metadata.MetaData;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jboss.netty.handler.codec.http.HttpVersion;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RestIndicesAction_ESTest extends RestIndicesAction_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // EXCEPTION DIFF:
      // The original version did not exhibit this exception:
      //     java.lang.NoClassDefFoundError : Could not initialize class org.elasticsearch.cluster.metadata.MetaData
      MetaData metaData0 = MetaData.PROTO;
      // EXCEPTION DIFF:
      // The modified version did not exhibit this exception:
      //     org.evosuite.runtime.mock.java.lang.MockIllegalArgumentException : invalid version format: CONTEXT_MODE
      HttpVersion httpVersion0 = null;
      try {
        httpVersion0 = new HttpVersion("context_mode", true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // invalid version format: CONTEXT_MODE
         //
         verifyException("org.jboss.netty.handler.codec.http.HttpVersion", e);
         assertTrue(e.getMessage().equals("invalid version format: CONTEXT_MODE"));   
      }
  }
}
